### ISSUE TITLE
Cell registration from nib

### ISSUE THREAD

**Issue by pavolkmet** [GoodRequest/GoodSwift#5]
Hello, what about a cell registration from Nib ?

```swift
func registerCell<T: UITableViewCell>(fromClass type: T.Type)  {
    register(UINib(nibName: String(describing: type), bundle: nil), forCellReuseIdentifier: String(describing: type))
}
```

**Comment by MarekSpalek** [comment]
Added in https://github.com/GoodRequest/GoodSwift/commit/50d6f4836f7f135aee21a529d32e9560e89ef5a5 and https://github.com/GoodRequest/GoodSwift/commit/4777914fd8114d8c3a598b9b5dbbd39866c1823d
